changelog:
  categories:
    - title: "Breaking changes"
      labels:
        - breaking changes
    
    - title: "New features"
      labels:
        - enhancement

    - title: "Bugs fixed"
      labels:
        - bug

    - title: "Other changes"
      labels:
        - "*"
