package channel

import (
	"errors"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/nyttikord/gokord/component"
	"github.com/nyttikord/gokord/discord"
	. "github.com/nyttikord/gokord/discord/request"
	"github.com/nyttikord/gokord/discord/types"
	"github.com/nyttikord/gokord/emoji"
	"github.com/nyttikord/gokord/user"
)

// A Message stores all data related to a specific Discord message.
type Message struct {
	ID        string `json:"id"`
	ChannelID string `json:"channel_id"`
	GuildID   string `json:"guild_id,omitempty"`
	// Content of the [Message].
	Content string `json:"content"`
	// The time at which the last edit of the [Message] occurred, if it has been edited.
	EditedTimestamp *time.Time `json:"edited_timestamp"`
	// The roles mentioned in the [Message].
	MentionRoles []string `json:"mention_roles"`
	// Whether the [Message] is text-to-speech.
	TTS bool `json:"tts"`
	// Whether the [Message] mentions everyone.
	MentionEveryone bool `json:"mention_everyone"`
	// The author of the [Message].
	// This is not guaranteed to be a valid user.User (webhook-sent messages do not possess a full author).
	Author *user.User `json:"author"`
	// A list of [MessageAttachment]s present in the [Message].
	Attachments []*MessageAttachment `json:"attachments"`
	// A list of [component.Message] attached to the [Message].
	Components []component.Message `json:"-"`
	// A list of [MessageEmbed] present in the [Message].
	Embeds []*MessageEmbed `json:"embeds"`
	// A list of [user.User]s mentioned in the [Message].
	Mentions []*user.User `json:"mentions"`
	// A list of [Reactions] to the [Message].
	Reactions []*Reactions `json:"reactions"`
	// Whether the [Message] is pinned or not.
	Pinned bool `json:"pinned"`
	// Type of the [Message].
	Type types.Message `json:"type"`
	// [Webhook.ID] of the [Message], if it was generated by a [Webhook].
	WebhookID string `json:"webhook_id"`
	// Member properties for this message's author, contains only partial information.
	Member *user.Member `json:"member"`
	// [channel.Channel]s specifically mentioned in this [Message].
	//
	// Not all channel mentions in a message will appear.
	// Only textual channels that are visible to everyone in a lurkable guild.Guild will be included.
	// Only crossposted messages (via Channel Following) currently include this at all.
	MentionChannels []*Channel `json:"mention_channels"`
	// Is sent with Rich Presence-related chat embeds.
	Activity *MessageActivity `json:"activity"`
	// Is sent with Rich Presence-related chat embeds.
	Application *MessageApplication `json:"application"`
	// MessageReference contains [MessageReference] data sent with crossposted or reply [Message]s.
	// This does not contain the reference *to* this Message;
	// this is for when *this* Message references another.
	//
	// To generate a reference to this message, use [Message.Reference].
	MessageReference *MessageReference `json:"message_reference"`
	// ReferencedMessage associated with the [MessageReference].
	//
	// NOTE: This field is only returned for messages with a type [types.MessageReply] or
	// [types.MessageThreadStarterMessage].
	// If the message is a reply but the ReferencedMessage field is not present,
	// the backend did not attempt to fetch the message that was being replied to, so its state is unknown.
	// If the field exists but is null, the referenced message was deleted.
	ReferencedMessage *Message `json:"referenced_message"`
	// The message associated with the [MessageReference].
	// This is a minimal subset of fields in a [Message] (e.g. Author is excluded)
	//
	// NOTE: This field is only returned when referenced when [MessageReference.Type] is
	// [types.MessageReferenceForward].
	MessageSnapshots []MessageSnapshot `json:"message_snapshots"`
	// InteractionMetadata is sent when the [Message] is a response to an [interaction.Interaction], without an existing
	// [Message].
	// This means responses to [Message] component interactions do not include this property,
	// instead including a [MessageReference], as components exist on preexisting messages.
	InteractionMetadata *MessageInteractionMetadata `json:"interaction_metadata"`
	// Flags of the [Message], which describe extra features of a [Message].
	Flags MessageFlags `json:"flags"`
	// Thread that was started from this [Message], includes thread member object.
	Thread *Channel `json:"thread,omitempty"`
	// StickerItems represents sent [emoji.Sticker]s, if there were any.
	StickerItems []*emoji.StickerItem `json:"sticker_items"`
	// Poll contained in the [Message].
	Poll *Poll `json:"poll"`
}

// GetCustomEmojis pulls out all the custom (Non-unicode) emojis from a [Message] and returns them.
func (m *Message) GetCustomEmojis() []*emoji.Emoji {
	var toReturn []*emoji.Emoji
	emojis := emoji.Regex.FindAllString(m.Content, -1)
	if len(emojis) < 1 {
		return toReturn
	}
	for _, em := range emojis {
		parts := strings.Split(em, ":")
		toReturn = append(toReturn, &emoji.Emoji{
			ID:       parts[2][:len(parts[2])-1],
			Name:     parts[1],
			Animated: strings.HasPrefix(em, "<a:"),
		})
	}
	return toReturn
}

// MessageFlags is the flags of [Message].
// https://discord.com/developers/docs/resources/channel#message-object-message-flags
type MessageFlags int

const (
	// MessageFlagsCrossPosted has been published to subscribed channels (via Channel Following).
	MessageFlagsCrossPosted MessageFlags = 1 << 0
	// MessageFlagsIsCrossPosted is originated from a message in another channel (via Channel Following).
	MessageFlagsIsCrossPosted MessageFlags = 1 << 1
	// MessageFlagsSuppressEmbeds does not include any embeds when serializing this message.
	MessageFlagsSuppressEmbeds MessageFlags = 1 << 2
	// MessageFlagsSourceMessageDeleted (via Channel Following).
	MessageFlagsSourceMessageDeleted MessageFlags = 1 << 3
	// MessageFlagsUrgent came from the urgent message system (official).
	MessageFlagsUrgent MessageFlags = 1 << 4
	// MessageFlagsHasThread with the same id as the message.
	MessageFlagsHasThread MessageFlags = 1 << 5
	// MessageFlagsEphemeral is only visible to the user who invoked the Interaction.
	MessageFlagsEphemeral MessageFlags = 1 << 6
	// MessageFlagsLoading is an Interaction Response and the bot is "thinking".
	MessageFlagsLoading MessageFlags = 1 << 7
	// MessageFlagsFailedToMentionSomeRolesInThread and add their members to the thread.
	MessageFlagsFailedToMentionSomeRolesInThread MessageFlags = 1 << 8
	// MessageFlagsSuppressNotifications will not trigger push and desktop notifications.
	MessageFlagsSuppressNotifications MessageFlags = 1 << 12
	MessageFlagsIsVoiceMessage        MessageFlags = 1 << 13
	// MessageFlagsHasSnapshot (via Message Forwarding)
	MessageFlagsHasSnapshot = 1 << 14
	// MessageFlagsIsComponentsV2 this message uses the new components system.
	// Disables the ability of sending `content` and `embeds`
	MessageFlagsIsComponentsV2 MessageFlags = 1 << 15
)

// A MessageAttachment stores data for message attachments.
type MessageAttachment struct {
	ID           string                 `json:"id"`
	Filename     string                 `json:"filename,omitempty"`
	Title        string                 `json:"title"`
	Description  string                 `json:"description"`
	ContentType  string                 `json:"content_type"`
	Size         int                    `json:"size"`
	URL          string                 `json:"url"`
	ProxyURL     string                 `json:"proxy_url"`
	Width        int                    `json:"width,omitempty"`
	Height       int                    `json:"height,omitempty"`
	Ephemeral    bool                   `json:"ephemeral,omitempty"`
	DurationSecs float64                `json:"duration_secs,omitempty"`
	Waveform     string                 `json:"waveform,omitempty"`
	Flags        MessageAttachmentFlags `json:"flags,omitempty"`
}

// MessageAttachmentFlags is the flags of a [MessageAttachment].
type MessageAttachmentFlags int

const (
	MessageAttachmentFlagsIsRemix MessageAttachmentFlags = 1 << 2
)

// MessageActivity is sent with Rich Presence-related chat embeds.
type MessageActivity struct {
	Type    types.MessageActivity `json:"type"`
	PartyID string                `json:"party_id"`
}

// MessageApplication is sent with Rich Presence-related chat embeds.
type MessageApplication struct {
	ID          string `json:"id"`
	CoverImage  string `json:"cover_image"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Name        string `json:"name"`
}

// MessageSnapshot represents a snapshot of a forwarded [Message].
// https://discord.com/developers/docs/resources/message#message-snapshot-object
type MessageSnapshot struct {
	Message *Message `json:"message"`
}

// MessageReference contains reference data sent with crossposted [Message]s.
type MessageReference struct {
	Type            types.MessageReference `json:"type,omitempty"`
	MessageID       string                 `json:"message_id"`
	ChannelID       string                 `json:"channel_id,omitempty"`
	GuildID         string                 `json:"guild_id,omitempty"`
	FailIfNotExists *bool                  `json:"fail_if_not_exists,omitempty"`
}

func (m *Message) reference(refType types.MessageReference, failIfNotExists bool) *MessageReference {
	return &MessageReference{
		Type:            refType,
		GuildID:         m.GuildID,
		ChannelID:       m.ChannelID,
		MessageID:       m.ID,
		FailIfNotExists: &failIfNotExists,
	}
}

// Reference returns a MessageReference of the given [Message].
func (m *Message) Reference() *MessageReference {
	return m.reference(types.MessageReferenceDefault, true)
}

// SoftReference returns a MessageReference of the given [Message].
// If the message doesn't exist it will instead be sent as a non-reply [Message].
func (m *Message) SoftReference() *MessageReference {
	return m.reference(types.MessageReferenceDefault, false)
}

// Forward returns a MessageReference for a forwarded [Message].
func (m *Message) Forward() *MessageReference {
	return m.reference(types.MessageReferenceForward, true)
}

// ContentWithMentionsReplaced will replace all @<id> mentions with the username of the mention.
func (m *Message) ContentWithMentionsReplaced() (content string) {
	content = m.Content

	for _, u := range m.Mentions {
		content = strings.NewReplacer(
			"<@"+u.ID+">", "@"+u.Username,
			"<@!"+u.ID+">", "@"+u.Username,
		).Replace(content)
	}
	return
}

var PatternChannels = regexp.MustCompile("<#[^>]*>")

// ContentWithMoreMentionsReplaced will replace all @<id> mentions with the username of the mention, but also role IDs
// and more.
// TODO: remove from message package
//func (m *Message) ContentWithMoreMentionsReplaced(s *gokord.Session) (content string, err error) {
//	content = m.Content
//
//	if !s.StateEnabled {
//		content = m.ContentWithMentionsReplaced()
//		return
//	}
//
//	channel, err := s.State.Application(m.ChannelID)
//	if err != nil {
//		content = m.ContentWithMentionsReplaced()
//		return
//	}
//
//	for _, u := range m.Mentions {
//		nick := u.Username
//
//		member, err := s.State.Member(channel.GuildID, u.ID)
//		if err == nil && member.Nick != "" {
//			nick = member.Nick
//		}
//
//		content = strings.NewReplacer(
//			"<@"+u.ID+">", "@"+u.Username,
//			"<@!"+u.ID+">", "@"+nick,
//		).Replace(content)
//	}
//	for _, roleID := range m.MentionRoles {
//		role, err := s.State.Role(channel.GuildID, roleID)
//		if err != nil || !role.Mentionable {
//			continue
//		}
//
//		content = strings.Replace(content, "<@&"+role.ID+">", "@"+role.Name, -1)
//	}
//
//	content = patternChannels.ReplaceAllStringFunc(content, func(mention string) string {
//		channel, err := s.State.Application(mention[2 : len(mention)-1])
//		if err != nil || channel.Type == ChannelTypeGuildVoice {
//			return mention
//		}
//
//		return "#" + channel.Name
//	})
//	return
//}

// MessageInteractionMetadata contains metadata of [interaction.Interaction], including relevant [user.User] info.
type MessageInteractionMetadata struct {
	ID   string            `json:"id"`
	Type types.Interaction `json:"type"`
	// User who triggered the [interaction.Interaction].
	User *user.User `json:"user"`
	// IDs for installation context(s) related to an [interaction.Interaction].
	AuthorizingIntegrationOwners map[types.IntegrationInstall]string `json:"authorizing_integration_owners"`
	// ID of the original response [Message].
	//
	// NOTE: present only on followup [Message]s.
	OriginalResponseMessageID string `json:"original_response_message_id,omitempty"`
	// ID of the [Message] that contained interactive [component.Component].
	//
	// NOTE: present only on Message [component.Component] interactions.
	InteractedMessageID string `json:"interacted_message_id,omitempty"`
	// Metadata for [interaction.Interaction] that was used to open a modal.
	//
	// NOTE: present only on modal submit interactions.
	TriggeringInteractionMetadata *MessageInteractionMetadata `json:"triggering_interaction_metadata,omitempty"`
}

// MessageReaction stores the data for a message reaction.
type MessageReaction struct {
	UserID    string      `json:"user_id"`
	MessageID string      `json:"message_id"`
	Emoji     emoji.Emoji `json:"emoji"`
	ChannelID string      `json:"channel_id"`
	GuildID   string      `json:"guild_id,omitempty"`
}

// MessagePinned represents a pinned Message.
type MessagePinned struct {
	PinnedAt time.Time `json:"pinned_at"` // PinnedAt is the time when the message was pinned.
	Message  *Message  `json:"message"`   // Message pinned.
}

// MessagesPinned contains a list of MessagePinned in a channel.Channel.
type MessagesPinned struct {
	Items   []*MessagePinned `json:"items"`
	HasMore bool             `json:"has_more"`
}

var (
	ErrTooMuchStickers         = errors.New("too much stickers: cannot send more than 3 stickers")
	ErrTooMuchMessagesToDelete = errors.New("too much messages to delete: cannot delete more than 100 messages")
)

// ListMessages returns an array of [Message] the given [Channel].
//
// limit is the number messages that can be returned (max 100).
// If provided all messages returned will be before beforeID.
// If provided all messages returned will be after afterID.
// If provided all messages returned will be around aroundID.
func ListMessages(channelID string, limit int, beforeID, afterID, aroundID string) Request[[]*Message] {
	uri := discord.EndpointChannelMessages(channelID)

	v := url.Values{}
	if limit > 0 {
		v.Set("limit", strconv.Itoa(limit))
	}
	if afterID != "" {
		v.Set("after", afterID)
	}
	if beforeID != "" {
		v.Set("before", beforeID)
	}
	if aroundID != "" {
		v.Set("around", aroundID)
	}
	if len(v) > 0 {
		uri += "?" + v.Encode()
	}
	return NewData[[]*Message](http.MethodGet, uri)
}

// GetMessage from a given [Channel].
func GetMessage(channelID, messageID string) Request[*Message] {
	return NewData[*Message](http.MethodGet, discord.EndpointChannelMessage(channelID, messageID)).
		WithBucketID(discord.EndpointChannelMessage(channelID, ""))
}

// EditMessage, replacing it entirely with the given content.
func EditMessage(channelID, messageID, content string) Request[*Message] {
	return EditMessageComplex(NewMessageEdit(channelID, messageID).SetContent(content))
}

// EditMessageComplex, replacing it entirely with the given [MessageEdit].
func EditMessageComplex(m *MessageEdit) Request[*Message] {
	if m.Embeds != nil {
		for _, embed := range *m.Embeds {
			if embed.Type == "" {
				embed.Type = types.EmbedRich
			}
		}
	}

	endpoint := discord.EndpointChannelMessage(m.Channel, m.ID)

	if len(m.Files) == 0 {
		return NewData[*Message](http.MethodPatch, endpoint).
			WithBucketID(discord.EndpointChannelMessage(m.Channel, "")).WithData(m)
	}
	return NewMultipart[*Message](http.MethodPatch, endpoint, m, m.Files).
		WithBucketID(discord.EndpointChannelMessage(m.Channel, ""))
}

// DeleteMessage from the given [Channel].
func DeleteMessage(channelID, messageID string) Empty {
	req := NewSimple(http.MethodDelete, discord.EndpointChannelMessage(channelID, messageID)).
		WithBucketID(discord.EndpointChannelMessage(channelID, ""))
	return WrapAsEmpty(req)
}

// DeleteMessages from the [Channel].
//
// messages contains the list of message's ID to delete (max 100).
//
// If only one messageID is in the slice, it calls DeleteMessage.
// If the slice is empty, it does nothing.
func DeleteMessages(channelID string, messages []string) Empty {
	if len(messages) == 0 {
		// to do nothing
		return WrapErrorAsEmpty(nil)
	}

	if len(messages) == 1 {
		return DeleteMessage(channelID, messages[0])
	}

	if len(messages) > 100 {
		return WrapErrorAsEmpty(ErrTooMuchMessagesToDelete)
	}

	data := struct {
		Messages []string `json:"messages"`
	}{messages}

	req := NewSimple(http.MethodPost, discord.EndpointChannelMessagesBulkDelete(channelID)).WithData(data)
	return WrapAsEmpty(req)
}
