package channel

import (
	"io"
	"regexp"
	"strings"
	"time"

	"github.com/nyttikord/gokord/component"
	"github.com/nyttikord/gokord/discord/types"
	"github.com/nyttikord/gokord/emoji"
	"github.com/nyttikord/gokord/user"
)

// A Message stores all data related to a specific Discord message.
type Message struct {
	// The ID of the Message.
	ID string `json:"id"`

	// The ID of the channel in which the Message was sent.
	ChannelID string `json:"channel_id"`

	// The ID of the guild.Guild in which the Message was sent.
	GuildID string `json:"guild_id,omitempty"`

	// The content of the message.
	Content string `json:"content"`

	// The time at which the Message was sent.
	// CAUTION: this field may be removed in a
	// future API version; it is safer to calculate
	// the creation time via the ID.
	Timestamp time.Time `json:"timestamp"`

	// The time at which the last edit of the Message
	// occurred, if it has been edited.
	EditedTimestamp *time.Time `json:"edited_timestamp"`

	// The roles mentioned in the Message.
	MentionRoles []string `json:"mention_roles"`

	// Whether the Message is text-to-speech.
	TTS bool `json:"tts"`

	// Whether the Message mentions everyone.
	MentionEveryone bool `json:"mention_everyone"`

	// The author of the Message.
	// This is not guaranteed to be a valid user.User (webhook-sent messages do not possess a full author).
	Author *user.User `json:"author"`

	// A list of attachments present in the Message.
	Attachments []*MessageAttachment `json:"attachments"`

	// A list of components attached to the Message.
	Components []component.Message `json:"-"`

	// A list of embeds present in the Message.
	Embeds []*MessageEmbed `json:"embeds"`

	// A list of users mentioned in the Message.
	Mentions []*user.User `json:"mentions"`

	// A list of reactions to the Message.
	Reactions []*MessageReactions `json:"reactions"`

	// Whether the Message is pinned or not.
	Pinned bool `json:"pinned"`

	// The type of the Message.
	Type types.Message `json:"type"`

	// The webhook ID of the Message, if it was generated by a webhook.
	WebhookID string `json:"webhook_id"`

	// Member properties for this message's author, contains only partial information.
	Member *user.Member `json:"member"`

	// Channels specifically mentioned in this Message.
	//
	// Not all channel mentions in a message will appear.
	// Only textual channels that are visible to everyone in a lurkable guild.Guild will ever be included.
	// Only crossposted messages (via Channel Following) currently include this at all.
	MentionChannels []*Channel `json:"mention_channels"`

	// Is sent with Rich Presence-related chat embeds.
	Activity *MessageActivity `json:"activity"`

	// Is sent with Rich Presence-related chat embeds.
	Application *MessageApplication `json:"application"`

	// MessageReference contains reference data sent with crossposted or reply messages.
	// This does not contain the reference *to* this Message; this is for when *this* Message references another.
	// To generate a reference to this message, use Message.Reference.
	MessageReference *MessageReference `json:"message_reference"`

	// The message associated with the MessageReference.
	//
	// NOTE: This field is only returned for messages with a type types.MessageReply or types.MessageThreadStarterMessage.
	// If the message is a reply but the ReferencedMessage field is not present,
	// the backend did not attempt to fetch the message that was being replied to, so its state is unknown.
	// If the field exists but is null, the referenced message was deleted.
	ReferencedMessage *Message `json:"referenced_message"`

	// The message associated with the MessageReference.
	// This is a minimal subset of fields in a message (e.g. Author is excluded)
	//
	// NOTE: This field is only returned when referenced when MessageReference.Type is types.MessageReferenceForward.
	MessageSnapshots []MessageSnapshot `json:"message_snapshots"`

	// Interaction is sent when the Message is a response to an Interaction, without an existing Message.
	// This means responses to Message component interactions do not include this property,
	// instead including a MessageReference, as components exist on preexisting messages.
	//
	// Deprecated: use InteractionMetadata.
	Interaction *MessageInteraction `json:"interaction"`

	InteractionMetadata *MessageInteractionMetadata `json:"interaction_metadata"`

	// The flags of the Message, which describe extra features of a Message.
	// This is a combination of bit masks; the presence of a certain permission can
	// be checked by performing a bitwise AND between this int and the flag.
	Flags MessageFlags `json:"flags"`

	// The thread that was started from this Message, includes thread member object.
	Thread *Channel `json:"thread,omitempty"`

	// An array of StickerItem objects, representing sent stickers, if there were any.
	StickerItems []*emoji.StickerItem `json:"sticker_items"`

	// Poll contained in the Message.
	Poll *Poll `json:"poll"`
}

// GetCustomEmojis pulls out all the custom (Non-unicode) emojis from a message and returns a Slice of the Emoji struct.
func (m *Message) GetCustomEmojis() []*emoji.Emoji {
	var toReturn []*emoji.Emoji
	emojis := emoji.Regex.FindAllString(m.Content, -1)
	if len(emojis) < 1 {
		return toReturn
	}
	for _, em := range emojis {
		parts := strings.Split(em, ":")
		toReturn = append(toReturn, &emoji.Emoji{
			ID:       parts[2][:len(parts[2])-1],
			Name:     parts[1],
			Animated: strings.HasPrefix(em, "<a:"),
		})
	}
	return toReturn
}

// MessageFlags is the flags of Message
// https://discord.com/developers/docs/resources/channel#message-object-message-flags
type MessageFlags int

const (
	// MessageFlagsCrossPosted This message has been published to subscribed channels (via Channel Following).
	MessageFlagsCrossPosted MessageFlags = 1 << 0
	// MessageFlagsIsCrossPosted this message originated from a message in another channel (via Channel Following).
	MessageFlagsIsCrossPosted MessageFlags = 1 << 1
	// MessageFlagsSuppressEmbeds do not include any embeds when serializing this message.
	MessageFlagsSuppressEmbeds MessageFlags = 1 << 2
	// TODO: deprecated, remove when compatibility is not needed
	MessageFlagsSupressEmbeds MessageFlags = 1 << 2
	// MessageFlagsSourceMessageDeleted the source message for this crosspost has been deleted (via Channel Following).
	MessageFlagsSourceMessageDeleted MessageFlags = 1 << 3
	// MessageFlagsUrgent this message came from the urgent message system.
	MessageFlagsUrgent MessageFlags = 1 << 4
	// MessageFlagsHasThread this message has an associated thread, with the same id as the message.
	MessageFlagsHasThread MessageFlags = 1 << 5
	// MessageFlagsEphemeral this message is only visible to the user who invoked the Interaction.
	MessageFlagsEphemeral MessageFlags = 1 << 6
	// MessageFlagsLoading this message is an Interaction Response and the bot is "thinking".
	MessageFlagsLoading MessageFlags = 1 << 7
	// MessageFlagsFailedToMentionSomeRolesInThread this message failed to mention some roles and add their members to the thread.
	MessageFlagsFailedToMentionSomeRolesInThread MessageFlags = 1 << 8
	// MessageFlagsSuppressNotifications this message will not trigger push and desktop notifications.
	MessageFlagsSuppressNotifications MessageFlags = 1 << 12
	// MessageFlagsIsVoiceMessage this message is a voice message.
	MessageFlagsIsVoiceMessage MessageFlags = 1 << 13
	// MessageFlagsIsComponentsV2 this message uses the new components system. Disables the ability of sending `content` & `embeds`
	MessageFlagsIsComponentsV2 MessageFlags = 1 << 15
)

// File stores info about files you e.g. send in messages.
type File struct {
	Name        string
	ContentType string
	Reader      io.Reader
}

// A MessageAttachment stores data for message attachments.
type MessageAttachment struct {
	ID           string                 `json:"id"`
	URL          string                 `json:"url"`
	ProxyURL     string                 `json:"proxy_url"`
	Filename     string                 `json:"filename"`
	ContentType  string                 `json:"content_type"`
	Width        int                    `json:"width"`
	Height       int                    `json:"height"`
	Size         int                    `json:"size"`
	Ephemeral    bool                   `json:"ephemeral"`
	DurationSecs float64                `json:"duration_secs"`
	Waveform     string                 `json:"waveform"`
	Flags        MessageAttachmentFlags `json:"flags"`
}

// MessageAttachmentFlags is the flags of a message attachment.
type MessageAttachmentFlags int

const (
	MessageAttachmentFlagsIsRemix MessageAttachmentFlags = 1 << 2
)

// MessageReactions holds a reactions object for a message.
type MessageReactions struct {
	Count int          `json:"count"`
	Me    bool         `json:"me"`
	Emoji *emoji.Emoji `json:"emoji"`
}

// MessageActivity is sent with Rich Presence-related chat embeds
type MessageActivity struct {
	Type    types.MessageActivity `json:"type"`
	PartyID string                `json:"party_id"`
}

// MessageApplication is sent with Rich Presence-related chat embeds
type MessageApplication struct {
	ID          string `json:"id"`
	CoverImage  string `json:"cover_image"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
	Name        string `json:"name"`
}

// MessageSnapshot represents a snapshot of a forwarded message.
// https://discord.com/developers/docs/resources/message#message-snapshot-object
type MessageSnapshot struct {
	Message *Message `json:"message"`
}

// MessageReference contains reference data sent with crossposted messages.
type MessageReference struct {
	Type            types.MessageReference `json:"type,omitempty"`
	MessageID       string                 `json:"message_id"`
	ChannelID       string                 `json:"channel_id,omitempty"`
	GuildID         string                 `json:"guild_id,omitempty"`
	FailIfNotExists *bool                  `json:"fail_if_not_exists,omitempty"`
}

func (m *Message) reference(refType types.MessageReference, failIfNotExists bool) *MessageReference {
	return &MessageReference{
		Type:            refType,
		GuildID:         m.GuildID,
		ChannelID:       m.ChannelID,
		MessageID:       m.ID,
		FailIfNotExists: &failIfNotExists,
	}
}

// Reference returns a MessageReference of the given Message.
func (m *Message) Reference() *MessageReference {
	return m.reference(types.MessageReferenceDefault, true)
}

// SoftReference returns a MessageReference of the given Message.
// If the message doesn't exist it will instead be sent as a non-reply Message.
func (m *Message) SoftReference() *MessageReference {
	return m.reference(types.MessageReferenceDefault, false)
}

// Forward returns a MessageReference for a forwarded Message.
func (m *Message) Forward() *MessageReference {
	return m.reference(types.MessageReferenceForward, true)
}

// ContentWithMentionsReplaced will replace all @<id> mentions with the username of the mention.
func (m *Message) ContentWithMentionsReplaced() (content string) {
	content = m.Content

	for _, u := range m.Mentions {
		content = strings.NewReplacer(
			"<@"+u.ID+">", "@"+u.Username,
			"<@!"+u.ID+">", "@"+u.Username,
		).Replace(content)
	}
	return
}

var PatternChannels = regexp.MustCompile("<#[^>]*>")

// ContentWithMoreMentionsReplaced will replace all @<id> mentions with the username of the mention, but also role IDs
// and more.
// TODO: remove from message package
//func (m *Message) ContentWithMoreMentionsReplaced(s *gokord.Session) (content string, err error) {
//	content = m.Content
//
//	if !s.StateEnabled {
//		content = m.ContentWithMentionsReplaced()
//		return
//	}
//
//	channel, err := s.State.Channel(m.ChannelID)
//	if err != nil {
//		content = m.ContentWithMentionsReplaced()
//		return
//	}
//
//	for _, u := range m.Mentions {
//		nick := u.Username
//
//		member, err := s.State.Member(channel.GuildID, u.ID)
//		if err == nil && member.Nick != "" {
//			nick = member.Nick
//		}
//
//		content = strings.NewReplacer(
//			"<@"+u.ID+">", "@"+u.Username,
//			"<@!"+u.ID+">", "@"+nick,
//		).Replace(content)
//	}
//	for _, roleID := range m.MentionRoles {
//		role, err := s.State.Role(channel.GuildID, roleID)
//		if err != nil || !role.Mentionable {
//			continue
//		}
//
//		content = strings.Replace(content, "<@&"+role.ID+">", "@"+role.Name, -1)
//	}
//
//	content = patternChannels.ReplaceAllStringFunc(content, func(mention string) string {
//		channel, err := s.State.Channel(mention[2 : len(mention)-1])
//		if err != nil || channel.Type == ChannelTypeGuildVoice {
//			return mention
//		}
//
//		return "#" + channel.Name
//	})
//	return
//}

// MessageInteraction contains information about the gokord.Interaction which generated the Message.
type MessageInteraction struct {
	ID   string            `json:"id"`
	Type types.Interaction `json:"type"`
	Name string            `json:"name"`
	User *user.User        `json:"user"`

	// Member is only present when the interaction is from a guild.Guild.
	Member *user.Member `json:"member"`
}

// MessageInteractionMetadata contains metadata of gokord.Interaction, including relevant user.User info.
type MessageInteractionMetadata struct {
	// ID of the gokord.Interaction.
	ID string `json:"id"`
	// Type of the gokord.Interaction.
	Type types.Interaction `json:"type"`
	// User who triggered the gokord.Interaction.
	User *user.User `json:"user"`
	// IDs for installation context(s) related to an gokord.Interaction.
	AuthorizingIntegrationOwners map[types.Integration]string `json:"authorizing_integration_owners"`
	// ID of the original response Message.
	// NOTE: present only on followup messages.
	OriginalResponseMessageID string `json:"original_response_message_id,omitempty"`
	// ID of the Message that contained interactive component.Component.
	// NOTE: present only on Message component.Component interactions.
	InteractedMessageID string `json:"interacted_message_id,omitempty"`
	// Metadata for interaction that was used to open a modal.
	// NOTE: present only on modal submit interactions.
	TriggeringInteractionMetadata *MessageInteractionMetadata `json:"triggering_interaction_metadata,omitempty"`
}

// MessageReaction stores the data for a message reaction.
type MessageReaction struct {
	UserID    string      `json:"user_id"`
	MessageID string      `json:"message_id"`
	Emoji     emoji.Emoji `json:"emoji"`
	ChannelID string      `json:"channel_id"`
	GuildID   string      `json:"guild_id,omitempty"`
}
